### ISSUE TITLE
"Polynomial degree greater than 3-4 is unusual"

### ISSUE THREAD

**Issue by iamtekson** [ashokdahal/RiskChanges#11]
Generally speaking, it is unusual to use d greater than 3 or 4 because, for large values of d, the polynomial curve can become overly flexible and can take on some very strange shapes.

extracted from: https://machinelearningmastery.com/polynomial-features-transforms-for-machine-learning/

In the loss calculation, on [`getVulnerability function`](https://github.com/ashokdahal/RiskChanges/blob/master/RiskChanges/Compute_Loss_New.py#L151), we used a polynomial feature having a degree of 10.

**Comment by ashokdahal** [comment]
In our case we are trying to fit the line perfectly with the data points so that we can extract the values in between them rather than having a good fit equation. this is intentional overfitting to reduce the variance because the prediction values will always be in the range of and in between any given two points.
